include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "build/**"
    - "**.freezed.dart"
    - "**.g.dart"

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    prefer_asserts_with_message: false
    lines_longer_than_80_chars: false
    unnecessary_lambdas: false
    sort_constructors_first: false
    always_put_required_named_parameters_first: false