name: models
description: A models package for Qchat app.
version: 0.0.1

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  uuid: ^4.2.1

dev_dependencies:
  very_good_analysis: ^5.1.0