name: qchat
description: A chat client made with Flutter.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  envied: ^0.5.2
  flutter:
    sdk: flutter
  models:
    path: packages/models 

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
